[book]
authors = ["Beefman"]
language = "en"
multilingual = false
src = "src"
title = "An introduction to Hýyban"

[output.html]
default-theme = "ayu"
additional-css = [
    "res/leipzig.min.css",
    "res/style.css",
]