name: Deploy GitHub Pages

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Commit changes to gh-pages
        run: |
          rm -f .gitignore
          echo "node_modules" >> .gitignore
          echo "./bin" >> .gitignore
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git checkout -b tmp/gh-pages
          git add -A
          git commit -m "Update GitHub pages"
          git push origin tmp/gh-pages:gh-pages --force
